name: Sync Upstream

on:
  schedule:
    - cron: '0 */6 * * *' # Chạy tự động mỗi 6 tiếng
  workflow_dispatch: # Cho phép kích hoạt thủ công từ tab Actions

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add Upstream Remote and Fetch
        run: |
          git remote add upstream https://github.com/matom-dev/PMT_frontend.git
          git fetch upstream

      - name: Sync develop branch
        run: |
          git checkout -B develop origin/develop
          git merge upstream/develop -m "Merge upstream develop" --allow-unrelated-histories || echo "No changes or merge conflict in develop"
          git push origin develop

      - name: Sync main branch
        run: |
          git checkout -B main origin/main
          git merge upstream/main -m "Merge upstream main" --allow-unrelated-histories || echo "No changes or merge conflict in main"
          git push origin main
